### ISSUE TITLE
Error in describe.lsmeans

### ISSUE THREAD

**Issue by puterleat** [achetverikov/APAstats#1]
If I run:

```
m <- lm(mpg~factor(cyl), data=mtcars)
m.lsm <- lsmeans::lsmeans(m, ~cyl)
m.contrasts <- lsmeans::contrast(m.lsm, "eff")
describe.lsmeans(m.contrasts, 1)
```

I get an error I don't understand:

```
Error in x@linfct[i, , drop = FALSE] : subscript out of bounds
```

If it's any use, my current workaround is, but you may not want the dplyr and broom deps:

```
m.contrasts %>% 
  broom::tidy() %>% 
  transmute(markdownd=sprintf("difference = %.2f, _t_(%s) = %.2f, _p_ %s", 
                    .$estimate, 
                    apastats::f.round(.$statistic), 
                    .$df, 
                    apastats::round.p(.$p.value))) 

```

**Comment by achetverikov** [comment]
Thanks for the first ever bug report for `apastats`! The thing is that `describe.lsmeans` works with the _summary_ object from `lsmeans::contrasts`. It's described in the help file along with some examples. That is the intended behaviour because for some functions (`lmer`) computing the summary is computationally heavy, so you'd like to do it in some R chunk and cache it rather than compute it on each call to `describe.lsmeans`. I believe, that `broom::tidy()` does something similar to `summary(m.contrasts)`. 

So this should work:
```
m <- lm(mpg~factor(cyl), data=mtcars)
m.lsm <- lsmeans::lsmeans(m, ~cyl)
m.contrasts <- summary(lsmeans::contrast(m.lsm, "eff"))
describe.lsmeans(m.contrasts, 1)
```

**Comment by puterleat** [comment]
Apologies... should have read the examples properly!
